spring.application.name=vanloadingoptimiser

spring.datasource.url=jdbc:postgresql://localhost:5432/vanoptdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate